// <auto-generated />
using System;
using EmmascoTravelsApp1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmmascoTravelsApp1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250706192311_new")]
    partial class @new
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmmascoTravelsApp1.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TravelDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("EmmascoTravelsApp1.Models.CustomerService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("CustomerServices");
                });

            modelBuilder.Entity("EmmascoTravelsApp1.Models.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Package for Tokyo. This is a nice package to fit your journey ",
                            ImageUrl = "/image1/packageimg.jpg",
                            Name = "Tokyo",
                            Price = 100m
                        },
                        new
                        {
                            Id = 2,
                            Description = "This is package 2",
                            ImageUrl = "/image1/packageimg1.jpg",
                            Name = "Package 2",
                            Price = 200m
                        },
                        new
                        {
                            Id = 3,
                            Description = "This is package 3",
                            ImageUrl = "/image1/packageimg2.jpg",
                            Name = "Package 3",
                            Price = 300m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Package for Tokyo",
                            ImageUrl = "/image1/packageimg.jpg",
                            Name = "Tokyo",
                            Price = 100m
                        },
                        new
                        {
                            Id = 5,
                            Description = "This is package 2",
                            ImageUrl = "/image1/packageimg1.jpg",
                            Name = "Package 2",
                            Price = 200m
                        },
                        new
                        {
                            Id = 6,
                            Description = "This is package 3",
                            ImageUrl = "/image1/packageimg2.jpg",
                            Name = "Package 3",
                            Price = 300m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Package for Tokyo",
                            ImageUrl = "/image1/packageimg.jpg",
                            Name = "Tokyo",
                            Price = 100m
                        },
                        new
                        {
                            Id = 8,
                            Description = "This is package 2",
                            ImageUrl = "/image1/packageimg1.jpg",
                            Name = "Package 2",
                            Price = 200m
                        },
                        new
                        {
                            Id = 9,
                            Description = "This is package 3",
                            ImageUrl = "/image1/packageimg2.jpg",
                            Name = "Package 3",
                            Price = 300m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Package for Tokyo",
                            ImageUrl = "/image1/packageimg.jpg",
                            Name = "Tokyo",
                            Price = 100m
                        },
                        new
                        {
                            Id = 11,
                            Description = "This is package 2",
                            ImageUrl = "/image1/packageimg1.jpg",
                            Name = "Package 2",
                            Price = 200m
                        },
                        new
                        {
                            Id = 12,
                            Description = "This is package 3",
                            ImageUrl = "/image1/packageimg2.jpg",
                            Name = "Package 3",
                            Price = 300m
                        },
                        new
                        {
                            Id = 13,
                            Description = "Package for Tokyo",
                            ImageUrl = "/image1/packageimg.jpg",
                            Name = "Tokyo",
                            Price = 100m
                        },
                        new
                        {
                            Id = 14,
                            Description = "This is package 2",
                            ImageUrl = "/image1/packageimg1.jpg",
                            Name = "Package 2",
                            Price = 200m
                        },
                        new
                        {
                            Id = 15,
                            Description = "This is package 3",
                            ImageUrl = "/image1/packageimg2.jpg",
                            Name = "Package 3",
                            Price = 300m
                        });
                });

            modelBuilder.Entity("EmmascoTravelsApp1.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("EmmascoTravelsApp1.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
