// <auto-generated />
using System;
using EmmascoTravelsApp1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmmascoTravelsApp1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251123153644_AddTransaction")]
    partial class AddTransaction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmmascoTravelsApp1.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfPeople")
                        .HasColumnType("int");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentOption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TravelDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("EmmascoTravelsApp1.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("EmmascoTravelsApp1.Models.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accommodation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Activities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Meals")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Accommodation = "4-Star Hotel",
                            Activities = "Tokyo Tower, Shibuya Crossing, Mt. Fuji Tour",
                            Country = "Japan",
                            Description = "Package for Tokyo. This is a nice package to fit your journey, book and get started with our team",
                            Duration = "7 Days, 6 Nights",
                            ImageUrl = "/image1/packageimg.jpg",
                            Meals = "Breakfast Included",
                            Name = "Tokyo",
                            Price = 1700m,
                            Status = "Active",
                            Transport = "Flight + Bullet Train"
                        },
                        new
                        {
                            Id = 2,
                            Accommodation = "Customizable",
                            Activities = "Custom itinerary, Personalized tours",
                            Country = "Worldwide",
                            Description = "Customized Itenaries that you would match your prference",
                            Duration = "Flexible",
                            ImageUrl = "/image1/packageimg1.jpg",
                            Meals = "Optional",
                            Name = "Personal Trip",
                            Price = 2080m,
                            Status = "Active",
                            Transport = "Flexible Options"
                        },
                        new
                        {
                            Id = 3,
                            Accommodation = "3-Star Hotel",
                            Activities = "Great Wall, Forbidden City, Shanghai Tour",
                            Country = "China",
                            Description = "China's diverse landscapes include stunning forests, ranging from ancient tropical rainforests to towering mountain forests.",
                            Duration = "8 Days, 7 Nights",
                            ImageUrl = "/image1/packageimg2.jpg",
                            Meals = "Breakfast + Lunch",
                            Name = "Beijing",
                            Price = 2300m,
                            Status = "Active",
                            Transport = "Flight + High-speed Train"
                        },
                        new
                        {
                            Id = 4,
                            Accommodation = "4-Star Hotel",
                            Activities = "London Eye, Buckingham Palace, Stonehenge",
                            Country = "United Kingdom",
                            Description = "Rich blend of historical landmarks, cultural experiences, and scenic landscapes",
                            Duration = "10 Days, 9 Nights",
                            ImageUrl = "/image1/UK.jpg",
                            Meals = "Breakfast",
                            Name = "London",
                            Price = 4100m,
                            Status = "Active",
                            Transport = "Flight + Train"
                        },
                        new
                        {
                            Id = 5,
                            Accommodation = "Resort",
                            Activities = "Beaches, Island Tour, Snorkeling",
                            Country = "Barbados",
                            Description = "Inquire in Barbados's breeze, exceptional cultures, customs to see more, feel more, and know around the world.",
                            Duration = "6 Days, 5 Nights",
                            ImageUrl = "/image1/packageimg5.jpg",
                            Meals = "All Inclusive",
                            Name = "Bridgetown",
                            Price = 3000m,
                            Status = "Active",
                            Transport = "Flight + Local Transport"
                        },
                        new
                        {
                            Id = 6,
                            Accommodation = "Luxury Hotel",
                            Activities = "Burj Khalifa, Desert Safari, Shopping Tour",
                            Country = "UAE",
                            Description = "Habibi come to Dubai, get the best experience in Dubai",
                            Duration = "5 Days, 4 Nights",
                            ImageUrl = "/image1/packageimg10.jpg",
                            Meals = "Breakfast + Dinner",
                            Name = "Dubai",
                            Price = 1800m,
                            Status = "Active",
                            Transport = "Flight + Private Car"
                        },
                        new
                        {
                            Id = 7,
                            Accommodation = "3-Star Hotel",
                            Activities = "City Tour, Old Town, Zytglogge Clock Tower",
                            Country = "Switzerland",
                            Description = "Beautiful exploration and extraodinary people to meet and connect, vibe, believe and trust us with you little step",
                            Duration = "4 Days, 3 Nights",
                            ImageUrl = "/image1/packageimg4.jpg",
                            Meals = "Breakfast",
                            Name = "Bern",
                            Price = 1070m,
                            Status = "Active",
                            Transport = "Flight + Train"
                        },
                        new
                        {
                            Id = 8,
                            Accommodation = "4-Star Hotel",
                            Activities = "Pyramids of Giza, Nile Cruise, Egyptian Museum",
                            Country = "Egypt",
                            Description = "Explore Cairo with us to feels life's beauty, wonderful landscapes and their authentic city vibe they give",
                            Duration = "7 Days, 6 Nights",
                            ImageUrl = "/image1/packageimg11.jpg",
                            Meals = "Breakfast + Dinner",
                            Name = "Cairo",
                            Price = 2200m,
                            Status = "Active",
                            Transport = "Flight + Local Bus"
                        },
                        new
                        {
                            Id = 9,
                            Accommodation = "3-Star Hotel",
                            Activities = "Gateway of India, Taj Mahal, Bollywood Tour",
                            Country = "India",
                            Description = "Get the best of New Delhi, Mumbai with Emmasco Team, the coastals, cultures, and superb adventures",
                            Duration = "6 Days, 5 Nights",
                            ImageUrl = "/image1/packageimg6.jpg",
                            Meals = "Breakfast + Lunch",
                            Name = "New Delhi",
                            Price = 800m,
                            Status = "Active",
                            Transport = "Flight + Train"
                        },
                        new
                        {
                            Id = 10,
                            Accommodation = "Family Suites / Villas",
                            Activities = "Theme Parks, Family Adventures, Museums",
                            Country = "Worldwide",
                            Description = "Looking for family?? no worries we're here for you, look our awesome customized itenaries to enjoy lifetime moments with your family",
                            Duration = "Flexible",
                            ImageUrl = "/image1/package.jpg",
                            Meals = "Customizable",
                            Name = "Family Trip (Customized)",
                            Price = 1900m,
                            Status = "Active",
                            Transport = "Flight + Private Van"
                        },
                        new
                        {
                            Id = 11,
                            Accommodation = "Shared Apartments / Hotels",
                            Activities = "Nightlife, Beaches, Hiking",
                            Country = "Various Destinations",
                            Description = "Enjoy our amazing friendship packages that suit your needs of personalization",
                            Duration = "5 Days, 4 Nights",
                            ImageUrl = "/image1/packageimg3.jpg",
                            Meals = "Breakfast + Drinks",
                            Name = "Friendship Travel",
                            Price = 2000m,
                            Status = "Active",
                            Transport = "Flight + Local Bus"
                        },
                        new
                        {
                            Id = 12,
                            Accommodation = "3-Star Hotel",
                            Activities = "Northern Lights, Helsinki Tour, Snow Activities",
                            Country = "Finland",
                            Description = "Get to know more about Finland and get to the history of their customs, values and landscapes",
                            Duration = "5 Days, 4 Nights",
                            ImageUrl = "/image1/FINLANDO.jpg",
                            Meals = "Breakfast",
                            Name = "Helsinki",
                            Price = 500m,
                            Status = "Active",
                            Transport = "Flight + Train"
                        },
                        new
                        {
                            Id = 13,
                            Accommodation = "Luxury Hotel",
                            Activities = "Alps Hiking, Lake Alpsee, Rhine Valley Tour",
                            Country = "Germany",
                            Description = "Unforgettable memories you will get, explore the beauty of Berlin and hikings etc book with us to see",
                            Duration = "8 Days, 7 Nights",
                            ImageUrl = "/image1/germanyapp.jpg",
                            Meals = "Breakfast + Dinner",
                            Name = "Berlin",
                            Price = 6500m,
                            Status = "Active",
                            Transport = "Flight + Train"
                        },
                        new
                        {
                            Id = 14,
                            Accommodation = "4-Star Hotel",
                            Activities = "Sydney Opera House, Great Barrier Reef, Melbourne Tour",
                            Country = "Australia",
                            Description = "Enjoy the breathtaking and the best moments in Melbourne",
                            Duration = "7 Days, 6 Nights",
                            ImageUrl = "/image1/broaustra.jpg",
                            Meals = "Breakfast",
                            Name = "Canberra",
                            Price = 1500m,
                            Status = "Active",
                            Transport = "Flight + Car Rental"
                        },
                        new
                        {
                            Id = 15,
                            Accommodation = "3-Star Hotel",
                            Activities = "Niagara Falls, Toronto CN Tower, National Parks",
                            Country = "Canada",
                            Description = "A trip to explore the coastal and the excitement in Ontario, Canada",
                            Duration = "6 Days, 5 Nights",
                            ImageUrl = "/image1/canada0000.jpg",
                            Meals = "Breakfast",
                            Name = "Toronto",
                            Price = 1000m,
                            Status = "Active",
                            Transport = "Flight + Train"
                        });
                });

            modelBuilder.Entity("EmmascoTravelsApp1.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("EmmascoTravelsApp1.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("EmmascoTravelsApp1.Models.Tracking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Trackings");
                });

            modelBuilder.Entity("EmmascoTravelsApp1.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentOption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("EmmascoTravelsApp1.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EmmascoTravelsApp1.Models.Booking", b =>
                {
                    b.HasOne("EmmascoTravelsApp1.Models.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("EmmascoTravelsApp1.Models.Review", b =>
                {
                    b.HasOne("EmmascoTravelsApp1.Models.Package", "Package")
                        .WithMany("Reviews")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("EmmascoTravelsApp1.Models.Tracking", b =>
                {
                    b.HasOne("EmmascoTravelsApp1.Models.Booking", "Booking")
                        .WithMany("Trackings")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("EmmascoTravelsApp1.Models.Booking", b =>
                {
                    b.Navigation("Trackings");
                });

            modelBuilder.Entity("EmmascoTravelsApp1.Models.Package", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
