// <auto-generated />
using System;
using EmmascoTravelsApp1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmmascoTravelsApp1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250830160019_AddTrackingWithRelation")]
    partial class AddTrackingWithRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmmascoTravelsApp1.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfPeople")
                        .HasColumnType("int");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TravelDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("EmmascoTravelsApp1.Models.CustomerService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("CustomerServices");
                });

            modelBuilder.Entity("EmmascoTravelsApp1.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("EmmascoTravelsApp1.Models.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Package for Tokyo. This is a nice package to fit your journey, book and get started with our team",
                            ImageUrl = "/image1/packageimg.jpg",
                            Name = "Tokyo",
                            Price = 1700m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Customized Itenaries that you would match your prference",
                            ImageUrl = "/image1/packageimg1.jpg",
                            Name = "Personal Trip",
                            Price = 2080m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Description = "China's diverse landscapes include stunning forests, ranging from ancient tropical rainforests to towering mountain forests.",
                            ImageUrl = "/image1/packageimg2.jpg",
                            Name = "China",
                            Price = 2300m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Rich blend of historical landmarks, cultural experiences, and scenic landscapes",
                            ImageUrl = "/image1/UK.jpg",
                            Name = "United Kingdom",
                            Price = 4100m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Inquire in Barbados's breeze, exceptional cultures, customs to see more, feel more, and know around the world.",
                            ImageUrl = "/image1/packageimg5.jpg",
                            Name = "Barbados",
                            Price = 3000m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Habibi come to Dubai, get the best experience in Dubai",
                            ImageUrl = "/image1/packageimg10.jpg",
                            Name = "Dubai",
                            Price = 1800m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Beautiful exploration and extraodinary people to meet and connect, vibe, believe and trust us with you little step",
                            ImageUrl = "/image1/packageimg4.jpg",
                            Name = "Bern",
                            Price = 1070m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Explore Cairo with us to feels life's beauty, wonderful landscapes and their authentic city vibe they give",
                            ImageUrl = "/image1/packageimg11.jpg",
                            Name = "Egypt",
                            Price = 2200m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Get the best of Mumbai with Emmasco Team, the coastals, cultures, and superb adventures",
                            ImageUrl = "/image1/packageimg6.jpg",
                            Name = "India",
                            Price = 800m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Looking for family?? no worries we're here for you, look our awesome customized itenaries to enjoy lifetime moments with your family",
                            ImageUrl = "/image1/package.jpg",
                            Name = "Family Trip (Customized)",
                            Price = 1900m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Enjoy our amazing friendship packages that suit your needs of personalization",
                            ImageUrl = "/image1/packageimg3.jpg",
                            Name = "Friendship Travel",
                            Price = 2000m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Get to know more about Finland and get to the history of their customs, values and landscapes",
                            ImageUrl = "/image1/FINLANDO.jpg",
                            Name = "Finland",
                            Price = 500m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Unforgettable memories you will get, explore the beauty of Switzerland and hikings etc book with us to see",
                            ImageUrl = "/image1/packaGE201.jpg",
                            Name = "Switzerland",
                            Price = 6500m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Enjoy the breathtaking and the best moments in Melbourne",
                            ImageUrl = "/image1/broaustra.jpg",
                            Name = "Australia",
                            Price = 1500m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 15,
                            Description = "A trip to explore the coastal and the excitement in Ontario, Canada",
                            ImageUrl = "/image1/canada0000.jpg",
                            Name = "Canada",
                            Price = 1000m,
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("EmmascoTravelsApp1.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("EmmascoTravelsApp1.Models.Tracking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Trackings");
                });

            modelBuilder.Entity("EmmascoTravelsApp1.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EmmascoTravelsApp1.Models.Booking", b =>
                {
                    b.HasOne("EmmascoTravelsApp1.Models.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("EmmascoTravelsApp1.Models.Tracking", b =>
                {
                    b.HasOne("EmmascoTravelsApp1.Models.Booking", "Booking")
                        .WithMany("Trackings")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("EmmascoTravelsApp1.Models.Booking", b =>
                {
                    b.Navigation("Trackings");
                });
#pragma warning restore 612, 618
        }
    }
}
